package com.bwei.ssp.fanjialinaaa.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bwei.ssp.fanjialinaaa.GreenDao.fan;
import com.bwei.ssp.fanjialinaaa.GreenDao.lin;

import com.bwei.ssp.fanjialinaaa.database.fanDao;
import com.bwei.ssp.fanjialinaaa.database.linDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fanDaoConfig;
    private final DaoConfig linDaoConfig;

    private final fanDao fanDao;
    private final linDao linDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fanDaoConfig = daoConfigMap.get(fanDao.class).clone();
        fanDaoConfig.initIdentityScope(type);

        linDaoConfig = daoConfigMap.get(linDao.class).clone();
        linDaoConfig.initIdentityScope(type);

        fanDao = new fanDao(fanDaoConfig, this);
        linDao = new linDao(linDaoConfig, this);

        registerDao(fan.class, fanDao);
        registerDao(lin.class, linDao);
    }
    
    public void clear() {
        fanDaoConfig.clearIdentityScope();
        linDaoConfig.clearIdentityScope();
    }

    public fanDao getFanDao() {
        return fanDao;
    }

    public linDao getLinDao() {
        return linDao;
    }

}
